
INSERT INTO Puestos (Nombre)
VALUES
('PROFESIONISTA'),
('AUXILIAR SERVICIOS CHOFER'),
('AUXILIAR ESPECIALIZADO'),
('OFICINISTA'),
('TECNICO'),
('TECNICO AUXILIAR'),
('ELECTRICISTA'),
('CABO LINIERO'),
('LINIERO'),
('AYUDANTE LINIERO'),
('JEFE DE OFICINA'),
('JEFE DE DEPARTAMENTO'),
('SUPERINTENDENTE'),
('SUPERVISOR'),
('AYUDANTE DE ELECTRICISTA'),
('PROFESIONISTA DE COMUNICACIONES'),
('TECNICO DE COMUNICACIONES'),
('TECNICO DE CONTROL'),
('ADMINISTRATIVO');


INSERT INTO Usuarios (Nombre, ApellidoPaterno, ApellidoMaterno, RPE, Password, Activo)
VALUES
('MARIA EUGENIA', 'SANTIAGO', 'SANTIAGO', '9FMHN', '1234', 1),
('AMAYRANI', 'HERNANDEZ', 'SANTIAGO', '9N64G', '1234', 1),
('GERARDO', 'JIMENEZ', 'CANSECO', '9B53P', '1234', 1),
('ANGELES LIZETTE', 'RIOS', 'HERNANDEZ', '9AX4D', '1234', 1),
('NERI DAVID', 'RAUS', 'MATUS', '9N640', '1234', 1),
('SHENY', 'OSORIO', 'DE LA CRUZ', '9N637', '1234', 1),
('NORMA', 'GUERRA', 'LOPEZ', '9L0KA', '1234', 1),
('EDGAR', 'CABRERA', 'ESPINOZA', '9AWTA', '1234', 1),
('JUAN CARLOS', 'HERNANDEZ', 'ALVAREZ', '9AX4Y', '1234', 1),
('ROGERIO', 'CALDERON', 'MARTINEZ', '9L09N', '1234', 1),
('JOSE MANUEL', 'DE LA CRUZ', 'LOPEZ', '9L0CV', '1234', 1),
('MAURO', 'GIRON', 'CORTES', '9AWTE', '1234', 1),
('VICTOR HUGO', 'RODRIGUEZ', 'DE LA CRUZ', '9AWTD', '1234', 1),
('JORGE', 'RITO', 'BENITEZ', '9L0K0', '1234', 1),
('JUAN CARLOS', 'VELAZQUEZ', 'PELAEZ', '9L0CN', '1234', 1),
('FELIPE', 'CARRASQUEDO', 'MORALES', '9FC8G', '1234', 1),
('LUIS MIGUEL', 'BAUTISTA', 'GALLEGOS', '9AX3C', '1234', 1),
('JOSE CRUZ', 'OSORIO', 'HENCHEST', '9L0DT', '1234', 1),
('IMBERT DE JESUS', 'GUZMAN', 'ROSADO', '9L0DR', '1234', 1),
('ROCSEL', 'OSORIO', 'LOPEZ', '9AX2U', '1234', 1),
('JULIO', 'ZARATE', 'PETRIZ', '9AWT8', '1234', 1),
('ARTURO', 'BAUTISTA', 'GALLEGOS', '9AWRK', '1234', 1),
('HEBERTO ELIEZER', 'LEON', 'GUERRA', '9L0CP', '1234', 1),
('LUIS DANIEL', 'VERA', 'MARTINEZ', '9FJEJ', '1234', 1),
('FABBIANI', 'DE LA CRUZ', 'OSORIO', '9N63W', '1234', 1),
('LUIS ANTONIO', 'PINEDA', 'MARTINEZ', '9N63Y', '1234', 1),
('OSCAR', 'JIMENEZ', 'SANCHEZ', '9N638', '1234', 1),
('RODRIGO', 'FLORES', 'MARTINEZ', '9FC8T', '1234', 1),
('LUIS FERNANDO', 'GUZMAN', 'SANTIAGO', '9L0DU', '1234', 1),
('LUIS ALBERTO', 'MARTINEZ', 'MARTINEZ', '9L0E3', '1234', 1),
('RICARDO', 'ALDINO', 'GOMEZ', '9AWT6', '1234', 1),
('FREDDY', 'GARCIA', 'DE JESUS', '9AX46', '1234', 1),
('JOSE BALDEMAR', 'GONZALEZ', 'FERNANDEZ', '9AWTF', '1234', 1),
('EDGARDO ARAM', 'LOPEZ', 'GUZMAN', '9L0RB', '1234', 1),
('JOSE DE JESUS', 'SANCHEZ', 'MATUS', '9AWV0', '1234', 1),
('EDUARDO', 'JIMENEZ', 'PINEDA', '9AX17', '1234', 1),
('JENNER', 'ENRIQUE', 'REVUELTA', '9N65X', '1234', 1),
('GUSTAVO', 'MENDOZA', 'CARBALLO', '9AX1M', '1234', 1),
('MARIANA DE JESUS', 'GOMEZ', 'CRUZ', '9AX0E', '1234', 1),
('CARLOS JAVIER', 'GIJON', 'LECHUGA', '9FA6E', '1234', 1),
('LUIS ENRIQUE', 'MENDEZ', 'BAUTISTA', '9FA6T', '1234', 1),
('RICARDO RENE', 'HERNANDEZ', 'SANCHEZ', '9L0J8', '1234', 1),
('OMAR SANTOS', 'DIAZ', 'GARCIA', '9DY6J', '1234', 1),
('ENRIQUE', 'GARCIA', 'OSORIO', '9AWVT', '1234', 1),
('ANDRES', 'RAMOS', 'DE LEON', '9N64J', '1234', 1),
('MANUEL ANTONIO', 'SANTOS', 'MATADAMAS', '9N657', '1234', 1),
('JESUS CLEMENTE', 'MENDOZA', 'SANCHEZ', '9N64P', '1234', 1),
('ELSA JOSEFINA', 'CRUZ', 'RUIZ', '9N64F', '1234', 1),
('JESUS', 'BENITEZ', 'MATIAS', '9N64U', '1234', 1),
('JESUS EFREN', 'CHAVEZ', 'VASQUEZ', '9AN1K', '1234', 1),
('AHUIZOTL RODOLFO', 'VICTORIA', 'GARCIA', '9AX5V', '1234', 1);



INSERT INTO UsuarioPuesto (IdUsuario, IdPuesto)
VALUES
(1, 1),   -- MARIA EUGENIA - PROFESIONISTA
(2, 2),   -- AMAYRANI - AUXILIAR SERVICIOS CHOFER
(3, 1),   -- GERARDO - PROFESIONISTA
(4, 3),   -- ANGELES LIZETTE - AUXILIAR ESPECIALIZADO
(5, 3),   -- NERI DAVID - AUXILIAR ESPECIALIZADO
(6, 4),   -- SHENY - OFICINISTA
(7, 1),   -- NORMA - PROFESIONISTA
(8, 5),   -- EDGAR - TECNICO
(9, 6),   -- JUAN CARLOS - TECNICO AUXILIAR
(10, 7),  -- ROGERIO - ELECTRICISTA
(11, 4),  -- JOSE MANUEL - OFICINISTA
(12, 8),  -- MAURO - CABO LINIERO
(13, 8),  -- VICTOR HUGO - CABO LINIERO
(14, 9),  -- JORGE - LINIERO
(15, 9),  -- JUAN CARLOS - LINIERO
(16, 9),  -- FELIPE - LINIERO
(17, 9),  -- LUIS MIGUEL - LINIERO
(18, 9),  -- JOSE CRUZ - LINIERO
(19, 9),  -- IMBERT DE JESUS - LINIERO
(20, 9),  -- ROCSEL - LINIERO
(21, 9),  -- JULIO - LINIERO
(22, 9),  -- ARTURO - LINIERO
(23, 9),  -- HEBERTO ELIEZER - LINIERO
(24, 10), -- LUIS DANIEL - AYUDANTE LINIERO
(25, 10), -- FABBIANI - AYUDANTE LINIERO
(26, 10), -- LUIS ANTONIO - AYUDANTE LINIERO
(27, 10), -- OSCAR - AYUDANTE LINIERO
(28, 5),  -- RODRIGO - TECNICO
(29, 6),  -- LUIS FERNANDO - TECNICO AUXILIAR
(30, 7),  -- LUIS ALBERTO - ELECTRICISTA
(31, 1),  -- RICARDO - PROFESIONISTA
(32, 5),  -- FREDDY - TECNICO
(33, 1),  -- JOSE BALDEMAR - PROFESIONISTA
(34, 1),  -- EDGARDO ARAM - PROFESIONISTA
(35, 1),  -- JOSE DE JESUS - PROFESIONISTA
(36, 5),  -- EDUARDO - TECNICO
(37, 4),  -- JENNER - OFICINISTA
(38, 5),  -- GUSTAVO - TECNICO
(39, 1),  -- MARIANA DE JESUS - PROFESIONISTA
(40, 8),  -- CARLOS JAVIER - CABO LINIERO
(41, 5),  -- LUIS ENRIQUE - TECNICO
(42, 6),  -- RICARDO RENE - TECNICO AUXILIAR
(43, 9),  -- OMAR SANTOS - LINIERO
(44, 9),  -- ENRIQUE - LINIERO
(45, 7),  -- ANDRES - ELECTRICISTA
(46, 10), -- MANUEL ANTONIO - AYUDANTE LINIERO
(47, 10), -- JESUS CLEMENTE - AYUDANTE LINIERO
(48, 4),  -- ELSA JOSEFINA - OFICINISTA
(49, 5),  -- JESUS - TECNICO
(50, 1),  -- JESUS EFREN - PROFESIONISTA
(51, 1);  -- AHUIZOTL RODOLFO - PROFESIONISTA




SELECT 
    CONCAT(u.Nombre, ' ', u.ApellidoPaterno, ' ', u.ApellidoMaterno) AS NombreCompleto,
    p.Nombre AS Puesto
FROM UsuarioPuesto up
INNER JOIN Usuarios u ON up.IdUsuario = u.Id
INNER JOIN Puestos p ON up.IdPuesto = p.Id
ORDER BY u.Id;


